import cv2
import numpy as np
import os
from advisor.face_parsing.onnx_inference import FaceParsingONNX

model_path = os.path.join("advisor", "face_parsing", "weights", "resnet18.onnx")

engine = FaceParsingONNX(model_path)

image_path = "test_face.jpg"
print(f"Loading {image_path}...")
raw_image = cv2.imread(image_path)

if raw_image is None:
    print("❌ Error: Could not find the image.")
else:
    print("🤖 Running BiSeNet AI...")
    # 1. Get the raw numerical mask (Replace this with your actual engine call)
    # mask = engine.predict(raw_image)
    
    # --- SIMULATING THE MASK FOR THIS SCRIPT (DELETE THIS IN YOUR CODE) ---
    # Assuming mask is generated by your engine:
    mask = engine.predict(raw_image) 
    # ----------------------------------------------------------------------

    print("✂️ Slicing facial features...")
    # 2. Separate the numerical mask into pure Black & White cookie-cutters
    background_mask = (mask == 0).astype(np.uint8) * 255
    skin_mask = (mask == 1).astype(np.uint8) * 255
    nose_mask = (mask == 2).astype(np.uint8) * 255
    lip_mask = np.isin(mask, [12, 13]).astype(np.uint8) * 255 # Usually 12/13 for lips in CelebAMask
    hair_mask = (mask == 17).astype(np.uint8) * 255 # Usually 17 for hair
    facial_mask = (~np.isin(mask,[0,16])).astype(np.uint8) * 255
    eye_mask = np.isin(mask, [4, 5]).astype(np.uint8) * 255
    # 3. Apply the cookie-cutters to the original color photo!
    # bitwise_and keeps the original color where the mask is white, and turns the rest black.
    color_skin = cv2.bitwise_and(raw_image, raw_image, mask=skin_mask)
    color_lips = cv2.bitwise_and(raw_image, raw_image, mask=lip_mask)
    color_hair = cv2.bitwise_and(raw_image, raw_image, mask=hair_mask)
    color_bg = cv2.bitwise_and(raw_image, raw_image, mask=background_mask)
    color_face = cv2.bitwise_and(raw_image, raw_image, mask=facial_mask)
    color_eye = cv2.bitwise_and(raw_image, raw_image, mask=eye_mask)

    # 4. Save the results to check the math
    os.makedirs("extraction_results", exist_ok=True)
    cv2.imwrite("extraction_results/1_isolated_skin.jpg", color_skin)
    cv2.imwrite("extraction_results/4_isolated_bg.jpg", color_bg)
    cv2.imwrite("extraction_results/2_isolated_lips.jpg", color_lips)
    cv2.imwrite("extraction_results/3_isolated_hair.jpg", color_hair)
    cv2.imwrite("extraction_results/5_isolated_facial.jpg", color_face)
    cv2.imwrite("extraction_results/6_isolated_eyes.jpg", color_eye)
    
    print("✅ Success! Open the 'extraction_results' folder.")